[project]
authors = ["tonyfast <tony.fast@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "research"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]
scrape-github = """
    echo "execute the github scraper" 
    && time jupyter nbconvert --inplace 
    --execute --ExecutePreprocessor.kernel_name python3 --ExecutePreprocessor.timeout 600 
    2025-03-27-github-graphql.ipynb
    && echo "generate report"
    && time jupyter nbconvert --to html --output-dir reports 2025-03-27-github-graphql.ipynb
"""
scrape-thingiverse = """
    echo "execute the thingiverse scraper" 
    && time jupyter nbconvert --inplace 
    --execute --ExecutePreprocessor.kernel_name python3 --ExecutePreprocessor.timeout 600 
    2025-03-27-thingiverse.ipynb
    && echo "generate report"
    && time jupyter nbconvert --to html --output-dir reports 2025-03-27-thingiverse.ipynb
"""
scrape-ravelry = """
    echo "execute the ravelry scraper" 
    && time jupyter nbconvert --inplace 
    --execute --ExecutePreprocessor.kernel_name python3 --ExecutePreprocessor.timeout 600 
    2025-02-24-ravelry.ipynb
    && echo "generate report"
    && time jupyter nbconvert --to html --output-dir reports 2025-02-24-ravelry.ipynb
"""

scrape-aggregate = """
    echo "aggregate the scraper results" 
    && time jupyter nbconvert --inplace 
    --execute --ExecutePreprocessor.kernel_name python3 --ExecutePreprocessor.timeout 600 
    2025-03-01-aggregate.ipynb
    && echo "generate report"
    && time jupyter nbconvert --to html --output-dir reports 2025-03-01-aggregate.ipynb
"""


[dependencies]
python = ">=3.13.2,<3.14"
python-dotenv = ">=1.1.0,<2"
nbclient = ">=0.10.2,<0.11"
ipykernel = ">=6.29.5,<7"
platformdirs = ">=4.3.7,<5"
pandas = ">=2.2.3,<3"
toolz = ">=1.0.0,<2"
jinja2 = ">=3.1.6,<4"
nbconvert = ">=7.16.6,<8"
requests-cache = ">=1.2.1,<2"

[pypi-dependencies]
python-graphql-client = ">=0.4.3, <0.5"
