name: scraper
run-name: ATscraper
on: [push]
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: prefix-dev/setup-pixi@v0.8.3
      with:
        pixi-version: v0.41.4
        cache: true
    - run: pixi run scrape-github
