name: scraper
run-name: ATscraper
on: [push]
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4    
    - uses: prefix-dev/setup-pixi@v0.8.3
      with:
        pixi-version: v0.41.4
        cache: true
        cache-key: scraper
    - run: pixi run scrape-github
