name: scraper
run-name: ATscraper
on: 
  schedule:
    # every 3am
    - cron: "0 3 * * *"
  push:
    branches: [main]
    # add automated notebooks
    paths:
      - 2025-03-27-github-graphql.ipynb
      - 2025-03-27-thingiverse.ipynb
      - 2025-02-24-ravelry.ipynb
      - pixi.toml
      - pixi.lock
      - .github/workflows/*
  pull_request:
    branches: ['*']
    paths:
      - 2025-03-27-github-graphql.ipynb
      - 2025-03-27-thingiverse.ipynb
      - 2025-02-24-ravelry.ipynb
      - pixi.toml
      - pixi.lock
      - .github/workflows/*
concurrency:
      group: "${{ github.workflow }}-${{ github.sha }}" 
      cancel-in-progress: false

permissions:
  contents: write
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
jobs:
  previous: 
    runs-on: ubuntu-latest
    environment: scraper
    steps:
    - name: Retrieve Previous Workflow ID
      uses: actions/github-script@v6
      with:
        script: |
          const workflows = await github.rest.actions.listRepoWorkflows({
            owner: context.repo.owner,
            repo: context.repo.repo
          });
          const workflow = workflows.data.workflows.find(w => w.name === process.env.GITHUB_WORKFLOW);
          const data = await github.rest.actions.listWorkflowRuns({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: workflow.id,
            status: 'success'
          });
    
          if (data.data.workflow_runs.length > 0) {
            core.setOutput('run_id', data.data.workflow_runs[0].id);
            core.info("run_id", data.data.workflow_runs[0].id);
          } else {
            core.info('No successful workflows found.');
          }

  github:
    runs-on: ubuntu-latest
    needs: previous
    environment: scraper
    steps:
    - uses: actions/checkout@v4    
    - uses: actions/download-artifact@v4
      continue-on-error: true
      with:
        name: data-github
        path: data
        run-id: ${{ steps.previous.outputs.run_id }}
    - uses: prefix-dev/setup-pixi@v0.8.3
      with:
        pixi-version: v0.41.4
        cache: true
        cache-key: scraper
    - run: pixi run scrape-github
    - uses: actions/upload-artifact@v4
      with:
        name: data-github
        path: data
    - uses: actions/upload-artifact@v4
      with:
        name: scrape-github-${{ github.run_number }}
        path: |
          2025-03-27-github-graphql.ipynb
          reports/2025-03-27-github-graphql.html
  ravelry:
    runs-on: ubuntu-latest
    needs: previous
    environment: scraper
    steps:
    - uses: actions/checkout@v4    
    - uses: actions/download-artifact@v4
      continue-on-error: true
      with:
        name: data-ravelry
        path: data
        run-id: ${{ steps.previous.outputs.run_id }}
    - uses: prefix-dev/setup-pixi@v0.8.3
      with:
        pixi-version: v0.41.4
        cache: true
        cache-key: scraper
    - run: pixi run scrape-ravelry
      env:
        RAVELRY_USERNAME: ${{secrets.RAVELRY_USERNAME}}
        RAVELRY_PASSWORD: ${{secrets.RAVELRY_PASSWORD}}
    - uses: actions/upload-artifact@v4
      with:
        name: data-ravelry
        path: data              
    - uses: actions/upload-artifact@v4
      with:
        name: scrape-ravelry-${{ github.run_number }}
        path: |
          2025-02-24-ravelry.ipynb
          reports/2025-02-24-ravelry.html
    
  thingiverse:
    runs-on: ubuntu-latest
    needs: previous
    environment: scraper
    steps:
    - uses: actions/checkout@v4    
    - uses: actions/download-artifact@v4
      continue-on-error: true
      with:
        name: data-thingiverse
        path: data
        run-id: ${{ steps.previous.outputs.run_id }}
    - uses: prefix-dev/setup-pixi@v0.8.3
      with:
        pixi-version: v0.41.4
        cache: true
        cache-key: scraper
    - run: pixi run scrape-thingiverse
      env:
        THINGIVERSE_ACCESS_TOKEN: ${{secrets.THINGIVERSE_ACCESS_TOKEN}}
    - uses: actions/upload-artifact@v4
      with:
        name: data-thingiverse
        path: data
    - uses: actions/upload-artifact@v4
      with:
        name: scrape-thingiverse-${{ github.run_number }}
        path: |
          2025-03-27-thingiverse.ipynb
          reports/2025-03-27-thingiverse.html

  
  aggregate:
    runs-on: ubuntu-latest
    environment: scraper
    continue-on-error: true
    needs: [github, thingiverse, ravelry]
    steps:
    - uses: actions/checkout@v4    
    - uses: prefix-dev/setup-pixi@v0.8.3
      with:
        pixi-version: v0.41.4
        cache: true
        # this should use hashfiles
        cache-key: scraper
    - uses: actions/download-artifact@v4
      with:
        patterns: data-*
        path: data
        merge-multiple: true
    - run: ls -lathr
    - run: pixi run scrape-aggregate
    - uses: actions/upload-artifact@v4
      with:
        name: report-aggregate-${{ github.run_number }}
        path: |
          at.json.gz

  search:
    runs-on: ubuntu-latest
    environment: scraper
    needs: aggregate
    steps:
    - uses: actions/checkout@v4    
    - uses: prefix-dev/setup-pixi@v0.8.3
      with:
        pixi-version: v0.41.4
        cache: true
        cache-key: scraper
    - uses: actions/download-artifact@v4
      with:
        name: report-aggregate-${{ github.run_number }}
    - run: pixi run search
    - uses: actions/upload-artifact@v4
      with:
        name: report-search-${{ github.run_number }}
        path: |
          2025-03-12-lunr.ipynb
          2025-03-12-lunr.html
    
  site:
    runs-on: ubuntu-latest
    needs: search
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5        
      with:
        python-version: "3.13"
    - run: gh repo clone a11yhood/site-settings
    - run: pip install ./site-settings
    - uses: actions/download-artifact@v4
      with:
        pattern: data-*
        merge-multiple: true
        path: data
    - uses: actions/download-artifact@v4
      with:
        pattern: report-*
        merge-multiple: true
    - run: python -m site_settings
    - run: rm -rf site-settings
    - run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"        
        git add .
        git commit -m "generated"
        git checkout -b gh-pages
        git merge -Xtheirs main
        git push --force origin gh-pages