name: scraper
run-name: ATscraper
on: 
  schedule:
    # every 3am
    - cron: "0 3 * * *"
  push:
    branches: [main]
    # add automated notebooks
    paths:
      - 2025-03-27-github-graphql.ipynb
      - 2025-03-27-thingiverse.ipynb
      - 2025-02-24-ravelry.ipynb
      - pixi.toml
      - pixi.lock
      - .github/workflows/*
  pull_request:
    branches: ['*']
    paths:
      - 2025-03-27-github-graphql.ipynb
      - 2025-03-27-thingiverse.ipynb
      - 2025-02-24-ravelry.ipynb
      - pixi.toml
      - pixi.lock
      - .github/workflows/*
concurrency:
      group: "${{ github.workflow }}-${{ github.sha }}" 
      cancel-in-progress: false

permissions:
  contents: write
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
jobs:
  github:
    runs-on: ubuntu-latest
    environment: scraper
    steps:
    - uses: actions/checkout@v4    
    - uses: actions/cache@v4
      with:
        path: data/github
        key: ${{ runner.os }}-github
    - uses: prefix-dev/setup-pixi@v0.8.3
      with:
        pixi-version: v0.41.4
        cache: true
        cache-key: scraper
    - run: pixi run scrape-github
    - uses: actions/upload-artifact@v4
      with:
        name: scrape-github-${{ github.run_number }}
        path: |
          2025-03-27-github-graphql.ipynb
          reports/2025-03-27-github-graphql.html
  ravelry:
    runs-on: ubuntu-latest
    environment: scraper
    steps:
    - uses: actions/checkout@v4    
    - uses: actions/cache@v4
      with:
        path: data/ravelry
        key: ${{ runner.os }}-ravelry
    - uses: prefix-dev/setup-pixi@v0.8.3
      with:
        pixi-version: v0.41.4
        cache: true
        cache-key: scraper
    - run: pixi run scrape-ravelry
      env:
        RAVELRY_USERNAME: ${{secrets.RAVELRY_USERNAME}}
        RAVELRY_PASSWORD: ${{secrets.RAVELRY_PASSWORD}}
    - uses: actions/upload-artifact@v4
      with:
        name: scrape-ravelry-${{ github.run_number }}
        path: |
          2025-02-24-ravelry.ipynb
          reports/2025-02-24-ravelry.html
    
  thingiverse:
    runs-on: ubuntu-latest
    environment: scraper
    steps:
    - uses: actions/checkout@v4    
    - name: cache scraped data
      uses: actions/cache@v4
      with:
        path: data/thingiverse
        key: ${{ runner.os }}-thingiverse
    - uses: prefix-dev/setup-pixi@v0.8.3
      with:
        pixi-version: v0.41.4
        cache: true
        cache-key: scraper
    - run: pixi run scrape-thingiverse
      env:
        THINGIVERSE_ACCESS_TOKEN: ${{secrets.THINGIVERSE_ACCESS_TOKEN}}
    - uses: actions/upload-artifact@v4
      with:
        name: scrape-thingiverse-${{ github.run_number }}
        path: |
          2025-03-27-thingiverse.ipynb
          reports/2025-03-27-thingiverse.html

  
  aggregate:
    runs-on: ubuntu-latest
    environment: scraper
    continue-on-error: true
    needs: [github, thingiverse, ravelry]
    steps:
    - uses: actions/checkout@v4    
    - uses: prefix-dev/setup-pixi@v0.8.3
      with:
        pixi-version: v0.41.4
        cache: true
        cache-key: scraper
    - name: backfill thingiverse cache
      uses: actions/cache@v4
      with:
        path: data/thingiverse
        key: ${{ runner.os }}-thingiverse
    - name: backfill ravelry cache
      uses: actions/cache@v4
      with:
        path: data/ravelry
        key: ${{ runner.os }}-ravelry
    - run: pixi run scrape-aggregate
  search:
    runs-on: ubuntu-latest
    environment: scraper
    needs: aggregate
    steps:
    - uses: actions/checkout@v4    
    - uses: prefix-dev/setup-pixi@v0.8.3
      with:
        pixi-version: v0.41.4
        cache: true
        cache-key: scraper
    - run: pixi run search
  site:
    uses: a11yhood/site-settings/.github/workflows/jekyll.yaml@main
    needs: search
    secrets: 
      personal_access_token: ${{ secrets.token }}