name: scraper
run-name: ATscraper
on: 
  schedule:
    # every 3am
    - cron: "0 3 * * *"
  push:
    branches: [main]
    # add automated notebooks
    pull_request:
      branches: ['*']
    paths:
      - 2025-03-27-github-graphql.ipynb
      - pixi.toml
      - pixi.lock
      - .github/workflows/*


permissions:
  contents: write
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
jobs:
  scrape:
    runs-on: ubuntu-latest
    environment: scraper
    steps:
    - uses: actions/checkout@v4    
    - uses: prefix-dev/setup-pixi@v0.8.3
      with:
        pixi-version: v0.41.4
        cache: true
        cache-key: scraper
    - run: pixi run scrape-github
    - run: pixi run scrape-thingiverse
      env:
        THINGIVERSE_ACCESS_TOKEN: {{secrets.THINGIVERSE_ACCESS_TOKEN}}
    - run: pixi run scrape-ravelry
      env:
        RAVELRY_USERNAME: {{secrets.RAVELRY_USERNAME}}
        RAVELRY_PASSWORD: {{secrets.RAVELRY_PASSWORD}}
    # - name: Upload static files as artifact
    #   id: deployment
    #   uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
    #   with:
    #     path: .
    - run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"        
        git add .
        git commit -m "generated"
        git checkout -b gh-pages
        git merge -Xtheirs main
        git push --force origin gh-pages
  # deploy:
  #   # Add a dependency to the build job
  #   needs: scrape
  #   permissions:
  #     pages: write      # to deploy to Pages
  #     id-token: write   # to verify the deployment originates from an appropriate source
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Deploy to GitHub Pages
  #       id: deployment
  #       uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action