name: scraper
run-name: ATscraper
on: 
  schedule:
    # every 3am
    - cron: "0 3 * * *"
  push:
    branches: [main]
    # add automated notebooks
    pull_request:
      branches: ['*']
    paths:
      - 2025-03-27-github-graphql.ipynb
      - 2025-03-27-thingiverse.ipynb
      - 2025-02-24-ravelry.ipynb
      - pixi.toml
      - pixi.lock
      - .github/workflows/*


permissions:
  contents: write
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
jobs:
  github:
    runs-on: ubuntu-latest
    environment: scraper
    concurrency:
      group: "${{ github.workflow }}-${{ github.ref }}" 
      cancel-in-progress: false
    steps:
    - uses: actions/checkout@v4    
    - uses: prefix-dev/setup-pixi@v0.8.3
      with:
        pixi-version: v0.41.4
        cache: true
        cache-key: scraper
    - run: pixi run scrape-github
  ravelry:
    runs-on: ubuntu-latest
    environment: scraper
    concurrency:
      group: "${{ github.workflow }}-${{ github.sha }}" 
      cancel-in-progress: false
    steps:
    - uses: actions/checkout@v4    
    - uses: prefix-dev/setup-pixi@v0.8.3
      with:
        pixi-version: v0.41.4
        cache: true
        cache-key: scraper
    - run: pixi run scrape-ravelry
      env:
        RAVELRY_USERNAME: ${{secrets.RAVELRY_USERNAME}}
        RAVELRY_PASSWORD: ${{secrets.RAVELRY_PASSWORD}}
  thingiverse:
    runs-on: ubuntu-latest
    environment: scraper
    concurrency:
      group: "${{ github.workflow }}-${{ github.ref }}" 
      cancel-in-progress: false
    steps:
    - uses: actions/checkout@v4    
    - uses: prefix-dev/setup-pixi@v0.8.3
      with:
        pixi-version: v0.41.4
        cache: true
        cache-key: scraper
    - run: pixi run scrape-thingiverse
      env:
        THINGIVERSE_ACCESS_TOKEN: ${{secrets.THINGIVERSE_ACCESS_TOKEN}}
  site:
    needs: [github, thingiverse, ravelry]
    uses: a11yhood/site-settings/.github/workflows/jekyll.yaml@main
    secrets: 
      personal_access_token: ${{ secrets.token }}