name: tmp
run-name: tmp
on: 
  push:
    branches: [main]
    
permissions:
  contents: write
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
jobs:
  previous: 
    runs-on: ubuntu-latest
    environment: scraper
    steps:
    - name: Retrieve Previous Workflow ID
      uses: actions/github-script@v6
      with:
        script: |
          const workflows = await github.rest.actions.listRepoWorkflows({
            owner: context.repo.owner,
            repo: context.repo.repo
          });
          const workflow = workflows.data.workflows.find(w => w.name === "scraper");
          const data = await github.rest.actions.listWorkflowRuns({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: workflow.id,
            status: 'success'
          });
          core.info("length", data.data.workflow_runs.length)
          if (data.data.workflow_runs.length > 0) {
            core.info(JSON.stringify(data.data["workflow_runs"]));
            core.setOutput('run_id', data.data.workflow_runs[0].id);
            core.info( data.data.workflow_runs[0].id);
          } else {
            core.info('No successful workflows found.');
          }
